spin_manifest_version = 2

[application]
name = "spin-monolith"
version = "0.1.0"
authors = ["kunjee17"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-monolith"

[component.spin-monolith]
source = "target/wasm32-wasi/release/spin_monolith.wasm"
allowed_outbound_hosts = []
files = ["templates/**/*.html"]
[component.spin-monolith.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
